from __future__ import annotations

import logging
from typing import List, Optional

from pydantic import BaseModel, Field

logger = logging.getLogger("meta_application_builder.spec_governance.rfc7807")


class ValidationErrorDetail(BaseModel):
    """Specific field-level validation failure breakdown."""

    field_path: str = Field(..., description="JSONPath or dot-notation path to the invalid field.")
    code: str = Field(..., description="Unique error code (e.g., MBR-001, MBR-004).")
    message: str = Field(..., description="Human-readable explanation of the validation failure.")


class ProblemDetails(BaseModel):
    """RFC-7807 compliant problem details structure for application builder API errors."""

    type: str = Field(
        default="about:blank",
        description="A URI reference that identifies the problem type.",
    )
    title: str = Field(..., description="A short, human-readable summary of the problem type.")
    status: int = Field(..., description="The HTTP status code generated by the origin server.")
    detail: str = Field(..., description="A human-readable explanation specific to this occurrence.")
    instance: str = Field(..., description="A URI reference that identifies the specific occurrence.")
    invalid_params: List[ValidationErrorDetail] = Field(
        default_factory=list,
        description="List of specific field-level validation errors.",
    )

    @classmethod
    def create(
        cls,
        status: int,
        title: str,
        detail: str,
        instance: str,
        code_prefix: str = "MBR",
        invalid_params: Optional[List[ValidationErrorDetail]] = None,
        error_type: str = "about:blank",
    ) -> ProblemDetails:
        """Factory method to produce structured RFC-7807 response objects and log error events."""
        logger.warning(
            "Generating RFC-7807 ProblemDetails: status=%d, title='%s', instance='%s', error_count=%d",
            status,
            title,
            instance,
            len(invalid_params) if invalid_params else 0,
        )
        return cls(
            type=error_type,
            title=title,
            status=status,
            detail=detail,
            instance=instance,
            invalid_params=invalid_params or [],
        )